### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bilbolodz**
Added:
- antifreeze feature (require DHT22 sensor)
- possibility to use optocoupler driven relay (active LOW not HIGH)
- possibility to power reset cube (require second relay and adding "r" command in python code)

### CODE REVIEW

**Comment by autopower** [comment]
unfortunately I can't compile code you inserted. Target yun, IDE 1.6.12, I'm missing something?
Trying to quickfix code.
Arduino: 1.6.12 (Windows 10), Board: "Arduino Yún"

In file included from the3.ino:10:0:

C:\Program Files (x86)\Arduino\libraries\DHTLib/dht.h:78:1: error: expected unqualified-id before numeric constant

 0

 ^

the3.ino: In function 'void loop()':

the3:309: error: 'DHT' was not declared in this scope

     int chk = DHT.read22(DHT_PIN);

               ^

the3.ino: At global scope:

the3:359: error: expected unqualified-id before numeric constant

 0

 ^

exit status 1
'DHT' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by autopower** [comment]
sure, but may be there's a problem with coexistence with other DHT (unified) libraries.

**Comment by autopower** [comment]
I can publish your code in separate directory, so anyone can use it, if needed.

**Comment by bilbolodz** [comment]
OK, as you wish. How about adding "r" command to python code to "power reset Cube"?

**Comment by autopower** [comment]
can you briefly explain condition when the 'r' command is issued from python side?

**Comment by bilbolodz** [comment]
I've noticed that Cube sometimes has network problems (doesn't respond from network requests) and it needs to be rebooted. The simplest way to reboot cube is to disconnect and after some time reconnect power supply. You can connect another relay to arduino and wire Cube power through it. My arduino code when receive "r" message via bridge turn off relay for a CUBE_RESET_TIME (1 second) and turn it on again. To make it working python code has to sent such message, so maybe it's a good idea to add next "command" to python (e.x. reset) to send such message to arduino?

**Pull request closed without merging**
