### PR TITLE
First install fixes; Mailer tweaks; Readme clarity

### PR DESCRIPTION
**Pull request by tobyspark**
Hello,

Thanks for writing thermeq3. I've been meaning to set this up for ages. I finally did, and lost some hours trying to figure out some things that were broken when you install the beta from scratch. This has fixes from that, and a bit of love to the readme to help any future me's of the past. Of course, I haven't tested this from scratch, so perhaps it's the same trap again...!

Thanks,

Toby

### CODE REVIEW

**Comment by autopower** [comment]
Great work!
Did you check zip file or just lib directory? Which is outated (my fault).

**Comment by tobyspark** [comment]
The first commit updates the lib directory with the contents of the beta zip. Figuring out that the lib directory had v200 in it was one of the things that I lost a few hours over!

In this PR the beta zip and version number are not updated. You should probably check it before people’s autoupdate grabs this =]

**Comment by autopower** [comment]
to be honest, I'm lost with github, how to commint all changes to master branch?

**Comment by tobyspark** [comment]
I think you got it, there!

As a suggestion, if you haven't downloaded the GitHub desktop app, you should try it. Making commits as you change things, piece by little piece, is really rewarding and has lots of subtle benefits you'll come to appreciate.

**Comment by autopower** [comment]
I did it via web interface. Desktop app didnt show anything.

**Comment by tobyspark** [comment]
Oh, and worth saying that the version number in the /lib files (ie. files under active development) is still v219, as per the beta zip. That should probably be bumped to v220, or somehow made clear it's not the v219 of the zip.

**Comment by tobyspark** [comment]
re. Desktop app – Yeah, it's not for the meta-actions like reviewing and merging pull requests. But it's great for your day to day. Seeing the commits as just zip updates with all the changes hidden and no context made things quite confusing, got in the way of trying to pitch in. Anyhoo. You must have spent many, many hours on this, and I suspect have learnt a lot on the way – and that's how things go. Props!

**Pull request merged**
